spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: sayHello
          uri: http://127.0.0.1:8082/
          predicates:
            - Path=/baidu
        - id: directBaidu
          uri: http://www.baidu.com
          predicates:
            - Path=/directBaidu

server:
  port: 8081
