spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: sayHello
          # 结合nacos，可以使用服务名
          uri: lb://hello
          predicates:
            - Path=/hello/**
          filters:
            # 使用拦截器做身份认证的过滤
            - name: AuthenticationFilter  # 身份认证
            - name: AuthorizationFilter # 鉴权
            - StripPrefix=1 # 去掉前缀
        - id: directBaidu
          uri: http://www.baidu.com
          predicates:
            - Path=/directBaidu

server:
  port: 8081
